"""Initial schema

Revision ID: 3254c910aa28
Revises: 
Create Date: 2025-10-31 12:20:18.046241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3254c910aa28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_breakers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('portfolio_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('portfolio_pnl_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('open_positions_count', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('triggered_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("trigger_type IN ('daily_loss', 'max_drawdown', 'volatility_spike', 'manipulation_detected', 'api_failure')", name='check_trigger_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_circuit_breaker_resolved', 'circuit_breakers', ['resolved'], unique=False)
    op.create_index('idx_circuit_breaker_time', 'circuit_breakers', ['triggered_at'], unique=False)
    op.create_table('markets',
    sa.Column('condition_id', sa.String(length=66), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform', sa.Enum('POLYMARKET', 'KALSHI', name='platform'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('is_disputed', sa.Boolean(), nullable=True),
    sa.Column('yes_token_id', sa.String(length=78), nullable=True),
    sa.Column('no_token_id', sa.String(length=78), nullable=True),
    sa.Column('yes_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('no_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('liquidity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('open_interest', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('bid_ask_spread', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('order_book_depth', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('category', sa.Enum('POLITICS', 'MACRO_FINANCE', 'CRYPTO', 'TECH', 'SCIENCE', 'SPORTS', 'WEATHER', 'CULTURE', 'OTHER', name='sector'), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('market_slug', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('outcome_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution_source', sa.String(length=500), nullable=True),
    sa.Column('uma_proposal_id', sa.String(length=100), nullable=True),
    sa.Column('manipulation_risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('oracle_attack_detected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('resolution_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index('idx_markets_active', 'markets', ['active', 'closed'], unique=False)
    op.create_index('idx_markets_category', 'markets', ['category'], unique=False)
    op.create_index('idx_markets_end_date', 'markets', ['end_date'], unique=False)
    op.create_index('idx_markets_liquidity', 'markets', ['liquidity'], unique=False)
    op.create_index('idx_markets_volume', 'markets', ['volume_24h'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('objective', sa.String(length=50), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objective_value', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('constraint_violations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('max_drawdown_observed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('passed_safety_gate', sa.Boolean(), nullable=True),
    sa.Column('deployed', sa.Boolean(), nullable=True),
    sa.Column('deployed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deployment_notes', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('trades_simulated', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opt_deployed', 'optimization_runs', ['deployed', 'deployed_at'], unique=False)
    op.create_index('idx_opt_run_time', 'optimization_runs', ['started_at'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_trade_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('roi', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('information_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_drawdown_duration_days', sa.Integer(), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('downside_deviation', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('var_95', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cvar_95', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('k_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ulcer_index', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_time_in_trade_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capital_efficiency', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calculated_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('period_start', sa.TIMESTAMP(), nullable=False),
    sa.Column('period_end', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("entity_type IN ('whale', 'portfolio', 'strategy')", name='check_entity_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_perf_entity_time', 'performance_metrics', ['entity_type', 'entity_id', 'calculated_at'], unique=False)
    op.create_index('idx_perf_window', 'performance_metrics', ['window_days', 'calculated_at'], unique=False)
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("value_type IN ('string', 'number', 'boolean', 'json')", name='check_value_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('idx_system_state_key', 'system_state', ['key'], unique=False)
    op.create_table('wallet_clusters',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=200), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('clustering_method', sa.String(length=50), nullable=True),
    sa.Column('member_addresses', sa.ARRAY(sa.String(length=42)), nullable=False),
    sa.Column('primary_address', sa.String(length=42), nullable=True),
    sa.Column('funding_source', sa.String(length=42), nullable=True),
    sa.Column('arkham_entity_id', sa.String(length=100), nullable=True),
    sa.Column('nansen_label', sa.String(length=100), nullable=True),
    sa.Column('first_seen', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_index('idx_wallet_cluster_confidence', 'wallet_clusters', ['confidence_score'], unique=False)
    op.create_index('idx_wallet_cluster_primary', 'wallet_clusters', ['primary_address'], unique=False)
    op.create_table('order_books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(length=66), nullable=False),
    sa.Column('token_id', sa.String(length=78), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('best_bid', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('best_ask', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('bid_size', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('ask_size', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('bids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spread', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('spread_bps', sa.Integer(), nullable=True),
    sa.Column('mid_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('micro_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('book_imbalance', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('liquidity_2pct', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('liquidity_5pct', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.condition_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orderbook_market_time', 'order_books', ['market_id', 'timestamp'], unique=False)
    op.create_index('idx_orderbook_token_time', 'order_books', ['token_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_order_books_timestamp'), 'order_books', ['timestamp'], unique=False)
    op.create_table('whales',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('pseudonym', sa.String(length=100), nullable=True),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('platform', sa.Enum('POLYMARKET', 'KALSHI', name='platform'), nullable=True),
    sa.Column('total_volume', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('active_positions', sa.Integer(), nullable=False),
    sa.Column('avg_trade_size', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('avg_hold_time', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trade_frequency', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('roi', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('k_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rolling_30d_sharpe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rolling_30d_winrate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rolling_90d_sharpe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rolling_90d_winrate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sharpe_ci_lower', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ci_upper', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_shrunk', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('category_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_category', sa.Enum('POLITICS', 'MACRO_FINANCE', 'CRYPTO', 'TECH', 'SCIENCE', 'SPORTS', 'WEATHER', 'CULTURE', 'OTHER', name='sector'), nullable=True),
    sa.Column('avg_price_impact', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('market_maker_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('cusum_statistic', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('edge_status', sa.String(length=20), nullable=True),
    sa.Column('last_cusum_check', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_copying_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_active', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['wallet_clusters.cluster_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index('idx_whale_category', 'whales', ['primary_category'], unique=False)
    op.create_index('idx_whale_copying_enabled', 'whales', ['is_copying_enabled'], unique=False)
    op.create_index('idx_whale_edge_status', 'whales', ['edge_status'], unique=False)
    op.create_index('idx_whale_quality_score', 'whales', ['quality_score', 'is_active'], unique=False)
    op.create_index('idx_whale_tier', 'whales', ['tier', 'is_active'], unique=False)
    op.create_table('edge_decay_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('whale_address', sa.String(length=42), nullable=False),
    sa.Column('test_type', sa.String(length=20), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('test_statistic', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('change_detected', sa.Boolean(), nullable=False),
    sa.Column('p_value', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('recent_sharpe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('recent_winrate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recent_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('drawdown_from_peak', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['whale_address'], ['whales.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edge_decay_change', 'edge_decay_logs', ['change_detected', 'timestamp'], unique=False)
    op.create_index('idx_edge_decay_whale_time', 'edge_decay_logs', ['whale_address', 'timestamp'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('whale_address', sa.String(length=42), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('position_id', sa.String(length=100), nullable=True),
    sa.Column('trade_id', sa.String(length=100), nullable=True),
    sa.Column('alerted', sa.Boolean(), nullable=True),
    sa.Column('alert_channel', sa.String(length=50), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("severity IN ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')", name='check_severity'),
    sa.ForeignKeyConstraint(['whale_address'], ['whales.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_severity_time', 'events', ['severity', 'timestamp'], unique=False)
    op.create_index('idx_events_type_time', 'events', ['event_type', 'timestamp'], unique=False)
    op.create_index('idx_events_whale_time', 'events', ['whale_address', 'timestamp'], unique=False)
    op.create_table('manipulation_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('whale_address', sa.String(length=42), nullable=False),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detection_method', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_trades', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('related_markets', sa.ARRAY(sa.String(length=66)), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('auto_resolved', sa.Boolean(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('flagged_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint("flag_type IN ('spoofing', 'wash_trading', 'oracle_attack', 'pump_dump', 'coordinated')", name='check_flag_type'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='check_severity'),
    sa.ForeignKeyConstraint(['whale_address'], ['whales.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manip_reviewed', 'manipulation_flags', ['reviewed', 'flagged_at'], unique=False)
    op.create_index('idx_manip_type_severity', 'manipulation_flags', ['flag_type', 'severity'], unique=False)
    op.create_index('idx_manip_whale_time', 'manipulation_flags', ['whale_address', 'flagged_at'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('market_id', sa.String(length=66), nullable=False),
    sa.Column('token_id', sa.String(length=78), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('filled_size', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('remaining_size', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('avg_fill_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('slippage_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('slippage_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_whale', sa.String(length=42), nullable=True),
    sa.Column('source_trade_id', sa.String(length=100), nullable=True),
    sa.Column('copy_mode', sa.Enum('IMMEDIATE', 'DELAYED', 'PARTIAL', 'CONDITIONAL', name='copymode'), nullable=True),
    sa.Column('copy_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=132), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('filled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('cancelled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("order_type IN ('LIMIT', 'MARKET', 'FOK', 'FAK', 'GTC')", name='check_order_type'),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='check_order_side'),
    sa.CheckConstraint("status IN ('PENDING', 'OPEN', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'FAILED')", name='check_order_status'),
    sa.ForeignKeyConstraint(['source_whale'], ['whales.address'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index('idx_orders_market', 'orders', ['market_id'], unique=False)
    op.create_index('idx_orders_source_whale', 'orders', ['source_whale'], unique=False)
    op.create_index('idx_orders_status_time', 'orders', ['status', 'created_at'], unique=False)
    op.create_table('positions',
    sa.Column('position_id', sa.String(length=100), nullable=False),
    sa.Column('user_address', sa.String(length=42), nullable=False),
    sa.Column('market_id', sa.String(length=66), nullable=False),
    sa.Column('condition_id', sa.String(length=66), nullable=True),
    sa.Column('token_id', sa.String(length=78), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('initial_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('percent_pnl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_fees_paid', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('market_title', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('POLITICS', 'MACRO_FINANCE', 'CRYPTO', 'TECH', 'SCIENCE', 'SPORTS', 'WEATHER', 'CULTURE', 'OTHER', name='sector'), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('redeemable', sa.Boolean(), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_loss_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('days_to_expiry', sa.Integer(), nullable=True),
    sa.Column('exit_at_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('source_whale', sa.String(length=42), nullable=True),
    sa.Column('entry_trade_id', sa.String(length=100), nullable=True),
    sa.Column('entry_order_id', sa.String(length=100), nullable=True),
    sa.Column('exit_order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('opened_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("outcome IN ('YES', 'NO', NULL)", name='check_position_outcome'),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED', 'LIQUIDATED')", name='check_position_status'),
    sa.ForeignKeyConstraint(['condition_id'], ['markets.condition_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_whale'], ['whales.address'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_index('idx_positions_market', 'positions', ['market_id'], unique=False)
    op.create_index('idx_positions_pnl', 'positions', ['percent_pnl'], unique=False)
    op.create_index('idx_positions_source_whale', 'positions', ['source_whale'], unique=False)
    op.create_index('idx_positions_status', 'positions', ['status'], unique=False)
    op.create_index('idx_positions_user_status', 'positions', ['user_address', 'status'], unique=False)
    op.create_index(op.f('ix_positions_market_id'), 'positions', ['market_id'], unique=False)
    op.create_index(op.f('ix_positions_user_address'), 'positions', ['user_address'], unique=False)
    op.create_table('trades',
    sa.Column('trade_id', sa.String(length=100), nullable=False),
    sa.Column('trader_address', sa.String(length=42), nullable=False),
    sa.Column('market_id', sa.String(length=66), nullable=False),
    sa.Column('condition_id', sa.String(length=66), nullable=True),
    sa.Column('token_id', sa.String(length=78), nullable=False),
    sa.Column('event_slug', sa.String(length=200), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('market_title', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('category', sa.Enum('POLITICS', 'MACRO_FINANCE', 'CRYPTO', 'TECH', 'SCIENCE', 'SPORTS', 'WEATHER', 'CULTURE', 'OTHER', name='sector'), nullable=True),
    sa.Column('transaction_hash', sa.String(length=66), nullable=True),
    sa.Column('maker_address', sa.String(length=42), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('pre_trade_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('post_trade_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('price_impact_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('book_spread_at_trade', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_whale_trade', sa.Boolean(), nullable=True),
    sa.Column('followed', sa.Boolean(), nullable=True),
    sa.Column('our_order_id', sa.String(length=100), nullable=True),
    sa.Column('copy_mode', sa.Enum('IMMEDIATE', 'DELAYED', 'PARTIAL', 'CONDITIONAL', name='copymode'), nullable=True),
    sa.Column('copy_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('copy_latency_ms', sa.Integer(), nullable=True),
    sa.Column('copy_reason', sa.Text(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("outcome IN ('YES', 'NO', NULL)", name='check_trade_outcome'),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='check_trade_side'),
    sa.ForeignKeyConstraint(['trader_address'], ['whales.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index('idx_trades_category_time', 'trades', ['category', 'timestamp'], unique=False)
    op.create_index('idx_trades_market_time', 'trades', ['market_id', 'timestamp'], unique=False)
    op.create_index('idx_trades_timestamp', 'trades', ['timestamp'], unique=False)
    op.create_index('idx_trades_trader_time', 'trades', ['trader_address', 'timestamp'], unique=False)
    op.create_index('idx_trades_whale_followed', 'trades', ['is_whale_trade', 'followed'], unique=False)
    op.create_index(op.f('ix_trades_followed'), 'trades', ['followed'], unique=False)
    op.create_index(op.f('ix_trades_is_whale_trade'), 'trades', ['is_whale_trade'], unique=False)
    op.create_index(op.f('ix_trades_timestamp'), 'trades', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_timestamp'), table_name='trades')
    op.drop_index(op.f('ix_trades_is_whale_trade'), table_name='trades')
    op.drop_index(op.f('ix_trades_followed'), table_name='trades')
    op.drop_index('idx_trades_whale_followed', table_name='trades')
    op.drop_index('idx_trades_trader_time', table_name='trades')
    op.drop_index('idx_trades_timestamp', table_name='trades')
    op.drop_index('idx_trades_market_time', table_name='trades')
    op.drop_index('idx_trades_category_time', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_positions_user_address'), table_name='positions')
    op.drop_index(op.f('ix_positions_market_id'), table_name='positions')
    op.drop_index('idx_positions_user_status', table_name='positions')
    op.drop_index('idx_positions_status', table_name='positions')
    op.drop_index('idx_positions_source_whale', table_name='positions')
    op.drop_index('idx_positions_pnl', table_name='positions')
    op.drop_index('idx_positions_market', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_orders_status_time', table_name='orders')
    op.drop_index('idx_orders_source_whale', table_name='orders')
    op.drop_index('idx_orders_market', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_manip_whale_time', table_name='manipulation_flags')
    op.drop_index('idx_manip_type_severity', table_name='manipulation_flags')
    op.drop_index('idx_manip_reviewed', table_name='manipulation_flags')
    op.drop_table('manipulation_flags')
    op.drop_index('idx_events_whale_time', table_name='events')
    op.drop_index('idx_events_type_time', table_name='events')
    op.drop_index('idx_events_severity_time', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_edge_decay_whale_time', table_name='edge_decay_logs')
    op.drop_index('idx_edge_decay_change', table_name='edge_decay_logs')
    op.drop_table('edge_decay_logs')
    op.drop_index('idx_whale_tier', table_name='whales')
    op.drop_index('idx_whale_quality_score', table_name='whales')
    op.drop_index('idx_whale_edge_status', table_name='whales')
    op.drop_index('idx_whale_copying_enabled', table_name='whales')
    op.drop_index('idx_whale_category', table_name='whales')
    op.drop_table('whales')
    op.drop_index(op.f('ix_order_books_timestamp'), table_name='order_books')
    op.drop_index('idx_orderbook_token_time', table_name='order_books')
    op.drop_index('idx_orderbook_market_time', table_name='order_books')
    op.drop_table('order_books')
    op.drop_index('idx_wallet_cluster_primary', table_name='wallet_clusters')
    op.drop_index('idx_wallet_cluster_confidence', table_name='wallet_clusters')
    op.drop_table('wallet_clusters')
    op.drop_index('idx_system_state_key', table_name='system_state')
    op.drop_table('system_state')
    op.drop_index('idx_perf_window', table_name='performance_metrics')
    op.drop_index('idx_perf_entity_time', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index('idx_opt_run_time', table_name='optimization_runs')
    op.drop_index('idx_opt_deployed', table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index('idx_markets_volume', table_name='markets')
    op.drop_index('idx_markets_liquidity', table_name='markets')
    op.drop_index('idx_markets_end_date', table_name='markets')
    op.drop_index('idx_markets_category', table_name='markets')
    op.drop_index('idx_markets_active', table_name='markets')
    op.drop_table('markets')
    op.drop_index('idx_circuit_breaker_time', table_name='circuit_breakers')
    op.drop_index('idx_circuit_breaker_resolved', table_name='circuit_breakers')
    op.drop_table('circuit_breakers')
    # ### end Alembic commands ###
